### ISSUE TITLE
RemindMe command

### ISSUE THREAD

**Issue by pratikyoff** [pratikyoff/dota-discord-bot#10]
A command which reminds user of a string, i.e. alarm
`!RemindMe <Something to remind> <time><time unit>`
Example:
`!RemindMe Build the RemindMe command 6hours`

**Comment by chiragvartak** [comment]
Let's also synonyms for `<time-unit>`.  
hours = hour= hrs = hr = h = HoURs (Case insensitive)  
seconds = secs = sec = second
etc.

**Comment by pratikyoff** [comment]
0afba4c904865e939ce066d9f69ecd869aa9c0a7
