### ISSUE TITLE
Too much noise?

### ISSUE THREAD

**Issue by chiragvartak** [pratikyoff/dota-discord-bot#13]
Each person's match now has a Dotabuff and Opendota link printed. (Awesome!) But this is done for every person, and it creates those Dotabuff and Opendota thumbnails. All this info clutters the chat with too much redundant info. I suggest the following changes:

1. Remove the Opendota link. It's just redundant info, and anyone can get that link from a Dotabuff link.
2. If two or more people play the same match, print only a single Dotabuff link. But fixing issue #4 should resolve this.

Opinions?

**Comment by pratikyoff** [comment]
Fixed in 40ac9becddcf07ca55a75fbc53ee13d26f7bcb37
