### ISSUE TITLE
Cannot deploy bot on Mac

### ISSUE THREAD

**Issue by chiragvartak** [pratikyoff/dota-discord-bot#26]
When I try to do a `dotnet run` this is the output I get:

```
$ dotnet run
20181117 09:36:11 AM: Disconnecting from Discord.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Bot.Program.Main(String[] args) in /Users/<username>/github/dota-discord-bot/Bot/Program.cs:line 39
```

This is on the `dev` branch, commit `74ff0cc Added grimstroke to hero list`

**Comment by pratikyoff** [comment]
Fixed in acdcb6af80570e92eab57a809ff4bb96709b7ed8
A `token.txt` file containing the token of the bot is required to run the bot.
This file should be present in `Bot` folder.
