### ISSUE TITLE
Group the same match played by different players

### ISSUE THREAD

**Issue by chiragvartak** [pratikyoff/dota-discord-bot#4]
Currently, the bot simply prints the match details of every player. There is not indication as to if two or more players played the same match or different matches.  

Possible solutions:  
1. How about printing a line: @bacchan, @pkyo, @cocky played a match which they lost.
2. Simply print the match id for each person (but I don't like this solution too much)

(I know that different matches can be identified as different chat messages of the bot. But what if two players play two different matches, and finish it at almost the same time? Will happen rarely, I agree, but still.)

**Comment by abhinavmittal64** [comment]
A simple correction would be to just compare the game id from the dotabuff link and if it is same change the output format

**Comment by pratikyoff** [comment]
It's not that simple @abhinavmittal64 . Please go through the code and understand the code flow before making assumptions.

**Comment by abhinavmittal64** [comment]
I did @pratikyoff 
See what i am talking about it is you are using for each user right and then creating a string for each
what i am telling you to do is find the different matches played in that thread and then for each match print the details

**Comment by chiragvartak** [comment]
What's wrong with @abhinavmittal64's suggestion?

```
Get everyone's match id
Group those players whose match ids are the same
Print each group's match details one by one
```

I agree this will be more than just a simple modification.

**Comment by abhinavmittal64** [comment]
Simple as in not something where you would not need to spend too much time
i obviously can be wrong but you still got to make the changes right?
And what i am saying wouldn't require too much changes in the flow as far i have understood
point out why you think it would be unfeasible. only to learn not crying
